### ISSUE TITLE
Cross compilation problems

### ISSUE THREAD

**Issue by kie0tauB** [blas-lapack-rs/openblas-src#6]
When compiling from my Linux (debian stretch 64 bits) to my raspberry pi (version 1A, with raspbian jessy), I can compile my project depending on several external libraries with:

cargo build --target=arm-unknown-linux-gnueabihf

(and the ARM versions of all the libraries in a path that "ld for ARM" can find)

However, the only rust crate that doesn't compile is OpenBLAS, which insists in using my system's libraries (x86_64) instead of the ARM versions:

note: /path/to/my_project/target/arm-unknown-linux-gnueabihf/debug/build/openblas-provider-601a7b1eda73c46c/out/opt/OpenBLAS/lib/libopenblas.so: file not recognized: File format not recognized

**Comment by IvanUkhov** [comment]
Hi,

Thanks for the issue! The package wasn’t originally written with cross-compilation in mind, but cross-compilation is something that is certainly desirable. I don’t have such a concrete use case as you do, and I wouldn’t be able to test if I were to implement this. It’d be nice if you could tweak the package so that it compiles OpenBLAS the way you want and then open a pull request.

The steps taken to compile OpenBLAS are given in [build.rs](https://github.com/cmr/openblas-provider/blob/master/build.rs). You can try to adjust this script so that OpenBLAS gets compiled for your target architecture. The target architecture is given in the TARGET environment variable. As you can see, this variable is currently [being removed](https://github.com/cmr/openblas-provider/blob/master/build.rs#L27). As far as I remember, its format wasn’t appropriate for OpenBLAS’ build scripts, and it was throwing an error or something.

All in all, the way I see it, enabling cross-compilation requires figuring out how to process TARGET in order to make it suitable for OpenBLAS; perhaps some other options/environment variables are required.

Please feel free to ask questions. Thanks!

Best,
Ivan

**Comment by IvanUkhov** [comment]
[This section](https://github.com/xianyi/OpenBLAS#cross-compile) of OpenBLAS’ README might be helpful.

Best,
Ivan
